
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 19 15:47:25 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 32;
  public static final int LBRACKET = 41;
  public static final int INCREMENT = 37;
  public static final int MULT = 26;
  public static final int CONST = 21;
  public static final int LTEQ = 34;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 23;
  public static final int DECREMENT = 38;
  public static final int MINUS = 25;
  public static final int RPAREN = 7;
  public static final int AND = 35;
  public static final int LT = 33;
  public static final int OR = 36;
  public static final int COMMA = 8;
  public static final int CLASS = 20;
  public static final int DIV = 27;
  public static final int PLUS = 11;
  public static final int IF = 14;
  public static final int DOT = 40;
  public static final int FINDANY = 44;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 12;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int EQEQ = 29;
  public static final int NUMBER = 48;
  public static final int MOD = 28;
  public static final int IDENT = 49;
  public static final int BREAK = 19;
  public static final int VOID = 13;
  public static final int ARROW = 43;
  public static final int COLON = 39;
  public static final int FOREACH = 24;
  public static final int LBRACE = 3;
  public static final int ELSE = 15;
  public static final int READ = 18;
  public static final int CHARCONST = 47;
  public static final int WHILE = 16;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 46;
  public static final int EXTENDS = 22;
  public static final int PROG = 2;
  public static final int GT = 31;
  public static final int PRINT = 9;
  public static final int FINDANDREPLACE = 45;
  public static final int NOTEQ = 30;
}

